if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(SystemZ|s390x)")
  message(STATUS "Forcing characters to be signed, as on x86_64.")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsigned-char")
  message(STATUS "Cannot build WAMR on this platform, so WASM support is disabled.")
  set(FLB_WASM OFF)
  if(FLB_LUAJIT)
    if(NOT FLB_PREFER_SYSTEM_LIB_LUAJIT)
      message(WARNING "LuaJIT disabled. This platform does not support built in LuaJIT, please install LuaJIT as system lib and try again with FLB_PREFER_SYSTEM_LIB_LUAJIT on.")
      set(FLB_LUAJIT OFF)
    endif()
  endif()
endif ()
